spring:
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: ksadmin
      password: ksh110425!@
  datasource:
    url: jdbc:mariadb://localhost:3306/KS
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ksh110425!@
  jpa:
    open-in-view: false
    show-sql: true    # Hibernate 가 생성하는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true    # SQL 쿼리를 보기 쉽게 포맷팅하여 출력합니다.
        use_sql_comments: true    # SQL 쿼리에 주석을 추가
        highlight_sql: true   # SQL 쿼리를 하이라이트하여 출력
        auto_quote_keyword: true    # SQL 키워드를 자동으로 인용하여 SQL 구문 오류를 방지합니다.
    hibernate:
      ddl-auto: update #validate로 변경 예정
    defer-datasource-initialization: true   # 데이터 소스 초기화를 지연시킵니다. 이는 데이터베이스 연결을 설정하기 전에 다른 초기화 로직을 완료할 수 있게 합니다.

  application:
    name: "KS"

server:
  port: 8080
  servlet:
    encoding:
      force: true
      enabled: true
      charset: utf-8